#pragma once

#include "Client_Macro.h"
#include <time.h>

//#define USE_IMGUI

////이게 기존 엔진 디파인이랑 충돌하기 때문에 옮겼다.





static const unsigned int g_iWinCX = 1280;
static const unsigned int g_iWinCY = 720;

enum LEVEL { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO,LEVEL_STAGE1,LEVEL_STAGE1_BOSSROOM, LEVEL_STAGE2, LEVEL_STAGE2_BOSSROOM, LEVEL_GAMEPLAY, LEVEL_BOSS,LEVEL_MAPTOOL,LEVEL_END };

extern HINSTANCE	g_hInst;
extern HWND		g_hWnd;

namespace Client {}

using namespace Client;
////////세이브와 관련된 내용들
enum MODELTAG {
	MODEL_FORK, 
	MODEL_FIONA,
	MODEL_STAGE1_DECORATION_1,
	MODEL_STAGE1_DECORATION_2,
	MODEL_STAGE1_DECORATION_3,
	MODEL_STAGE1_DECORATION_4,
	MODEL_STAGE1_DECORATION_5,
	MODEL_STAGE1_DECORATION_6,
	MODEL_STAGE1_DECORATION_7,
	MODEL_STAGE1_DECORATION_8,
	MODEL_STAGE1_MOUNTAIN_1,
	MODEL_STAGE1_MOUNTAIN_2,
	MODEL_STAGE1_MOUNTAIN_3,
	MODEL_STAGE1_MOUNTAIN_4,
	MODEL_STAGE1_MOUNTAIN_5,
	MODEL_STAGE1_MOUNTAIN_6,
	MODEL_STAGE1_MOUNTAIN_7,
	MODEL_STAGE1_MOUNTAIN_8,
	MODEL_STAGE1_MOUNTAIN_9,
	MODEL_STAGE1_MOUNTAIN_10,
	MODEL_STAGE1_MOUNTAIN_11,
	MODEL_STAGE1_MOUNTAIN_12,
	MODEL_STAGE1_MOUNTAIN_13,
	MODEL_STAGE1_MOUNTAIN_14,
	MODEL_STAGE1_SHIP_1,
	MODEL_STAGE1_SHIP_2,
	MODEL_STAGE1_WALL_1,
	MODEL_STAGE1_WALL_2,
	MODEL_STAGE1_WALL_3,
	MODEL_STAGE1_WALL_4,
	MODEL_STAGE1_WALL_5,
	MODEL_STAGE2_DECORATION_1,
	MODEL_STAGE2_DECORATION_2,
	MODEL_STAGE2_DECORATION_3,
	MODEL_STAGE2_DECORATION_4,
	MODEL_STAGE2_DECORATION_5,
	MODEL_STAGE2_DECORATION_6,
	MODEL_STAGE2_DECORATION_7,
	MODEL_STAGE2_DECORATION_8,
	MODEL_STAGE2_DECORATION_9,
	MODEL_STAGE2_DECORATION_10,
	MODEL_STAGE2_DECORATION_11,
	MODEL_STAGE2_DECORATION_12,
	MODEL_STAGE2_MOUNTAIN_1,
	MODEL_STAGE2_MOUNTAIN_2,
	MODEL_STAGE2_MOUNTAIN_3,
	MODEL_STAGE2_MOUNTAIN_4,
	MODEL_STAGE2_MOUNTAIN_5,
	MODEL_STAGE2_MOUNTAIN_6,
	MODEL_STAGE2_MOUNTAIN_7,
	MODEL_STAGE2_MOUNTAIN_8,
	MODEL_STAGE2_MOUNTAIN_9,
	MODEL_STAGE2_MOUNTAIN_10,
	MODEL_STAGE2_MOUNTAIN_11,
	MODEL_STAGE2_MOUNTAIN_12,
	MODEL_STAGE2_SNOW_1,
	MODEL_STAGE2_SNOW_2,
	MODEL_STAGE2_SNOW_3,
	MODEL_STAGE2_WALL_1,
	MODEL_STAGE2_WALL_2,
	MODEL_STAGE2_WALL_3,
	MODEL_STAGE2_WALL_4,
	MODEL_STAGE2_WALL_5,
	MODEL_VOLCANO_1,
	MODEL_VOLCANO_2,
	MODEL_VOLCANO_3,
	MODEL_VOLCANO_Rock_1,
	MODEL_VOLCANO_Rock_2,
	MODEL_MOUNTAIN_1,
	MODEL_MOUNTAIN_2,
	MODEL_MOUNTAIN_3,
	MODEL_MOUNTAIN_4,
	MODEL_MOUNTAIN_5,
	MODEL_MOUNTAIN_6,
	MODEL_SNOW_ROCK_1,
	MODEL_SNOW_ROCK_2,
	MODEL_SNOW_ROCK_3,
	MODEL_ROCK_1,
	MODEL_ROCK_2,
	MODEL_ROCK_3,
	MODEL_ROCK_4,
	MODEL_DECORATION_1,
	MODEL_DECORATION_2,
	MODEL_DECORATION_3,
	MODEL_DECORATION_4,
	MODEL_SNOW_1,
	MODEL_SNOW_2,
	MODEL_SNOW_3,
	MODEL_DOOR_1,
	MODEL_DOOR_2,
	MODEL_VOLCANO_FAR_1,
	MODEL_VOLCANO_FAR_2,
	MODEL_SNOWMOUNTAIN_FAR_1,
	MODEL_SNOWMOUNTAIN_FAR_2,
	MODEL_SUBDECORATION_1,
	MODEL_SUBDECORATION_2,
	MODEL_SUBDECORATION_3,
	MODEL_SUBDECORATION_4,
	MODEL_SUBDECORATION_5,
	MODEL_SUBDECORATION_6,
	MODEL_SUBDECORATION_7,
	MODEL_SUBDECORATION_8,
	MODEL_SUBDECORATION_9,
	MODEL_LIZARD,
	MODEL_GHOSTDEER,
	MODEL_HORSE,
	MODEL_CUBE,
	MODEL_POWERLIZARD,
	MODEL_RAVEN,
	MODEL_LAMP,
	MODEL_CATFISH,
	MODEL_DIEGO,
	MODEL_BOSS_DOKKAEBI,
	MODEL_BOSS_GRIFFIN,
	MODEL_BOSS_BEAR,
	MODEL_END
};

enum LAYERTAG {
	LAYER_STATIC,
	LAYER_PLAYER,
	LAYER_MONSTER,
	LAYER_END
};

enum OBJECTTAG {
	OBJECT_STATIC,
	OBJECT_PLAYER,
	OBJECT_LIZARD,
	OBJECT_GOSTDEER,
	OBJECT_HORSE,
	OBJECT_CUBE,
	OBJECT_POWERLIZARD,
	OBJECT_RAVEN,
	OBJECT_LAMP,
	OBJECT_CATFISH,
	OBJECT_DIEGO,
	OBJECT_BOSS_DOKKAEBI,
	OBJECT_BOSS_GRIFFIN,
	OBJECT_BOSS_BEAR,
	OBJECT_END
};

extern const wchar_t* g_pModelTag[MODEL_END];
extern const wchar_t* g_pLayerTag[LAYER_END];
extern const wchar_t* g_pPrototypeObjectTag[OBJECT_END];
////여기까지가 세이브와 관련된 내용들


enum MAGAZINETAG {
	GREENMAGAZINETENTH,
	GREENMAGAZINE,
	BLUEMAGAZINETENTH,
	BLUEMAGAZINE,
	DEFAULT,
	MAGAZINETYPE_END
};
extern int g_iMagazine[MAGAZINETYPE_END];



enum EasingTypeID
{
	TYPE_Linear = 0,

	TYPE_QuadIn = 1,
	TYPE_QuadOut,
	TYPE_QuadInOut,

	TYPE_CubicIn = 4,
	TYPE_CubicOut,
	TYPE_CubicInOut,

	TYPE_QuarticIn = 7,
	TYPE_QuarticOut,
	TYPE_QuarticInOut,

	TYPE_QuinticIn = 10,
	TYPE_QuinticOut,
	TYPE_QuinticInOut,

	TYPE_SinIn = 13,
	TYPE_SinOut,
	TYPE_SinInOut,

	TYPE_ExpoIn = 16,
	TYPE_ExpoOut,
	TYPE_ExpoInOut,

	TYPE_CircularIn = 19,
	TYPE_CircularOut,
	TYPE_CircularInOut,

	TYPE_ElasticIn = 22,
	TYPE_ElasticOut,
	TYPE_ElasticInOut,

	TYPE_BounceIn = 25,
	TYPE_BounceOut,


	TYPE_End
};